nodes:
  - id: "n0"
  - id: "n1"
  - id: "n2"
edges:
  - n1: "n0"
    n2: "n1"
    length: 1
  - n1: "n0"
    n2: "n2"
    length: 1
  - n1: "n1"
    n2: "n2"
    length: 1
triplets:
  - n1: "n0"
    n2: "n1"
    n3: "n2"
