objects:
  - id: "n0"
  - id: "n1"
  - id: "n2"
  - id: "n3"
  - id: "n4"
  - id: "n5"
  - id: "n6"
  - id: "n7"
  - id: "n8"
  - id: "n9"
  - id: "n10"
  - id: "n11"
edges:
  - n1: "n0"
    n2: "n1"
    length: 1
  - n1: "n0"
    n2: "n2"
    length: 1
  - n1: "n1"
    n2: "n2"
    length: 1
  - n1: "n1"
    n2: "n3"
    length: 1
  - n1: "n2"
    n2: "n3"
    length: 1
  - n1: "n2"
    n2: "n4"
    length: 1
  - n1: "n3"
    n2: "n4"
    length: 1
  - n1: "n3"
    n2: "n5"
    length: 1
  - n1: "n4"
    n2: "n5"
    length: 1
  - n1: "n5"
    n2: "n6"
    length: 1
  - n1: "n4"
    n2: "n6"
    length: 1
  - n1: "n6"
    n2: "n11"
    length: 1
  - n1: "n6"
    n2: "n10"
    length: 1
  - n1: "n0"
    n2: "n7"
    length: 1
  - n1: "n2"
    n2: "n7"
    length: 1
  - n1: "n2"
    n2: "n8"
    length: 1
  - n1: "n7"
    n2: "n8"
    length: 1
  - n1: "n7"
    n2: "n9"
    length: 1
  - n1: "n8"
    n2: "n9"
    length: 1
  - n1: "n8"
    n2: "n10"
    length: 1
  - n1: "n9"
    n2: "n10"
    length: 1
  - n1: "n10"
    n2: "n11"
    length: 1
triplets:
  - n1: "n0"
    n2: "n1"
    n3: "n2"
  - n1: "n1"
    n2: "n3"
    n3: "n2"
  - n1: "n2"
    n2: "n3"
    n3: "n4"
  - n1: "n3"
    n2: "n5"
    n3: "n4"
  - n1: "n4"
    n2: "n5"
    n3: "n6"
  - n1: "n0"
    n2: "n2"
    n3: "n7"
  - n1: "n7"
    n2: "n2"
    n3: "n8"
  - n1: "n7"
    n2: "n8"
    n3: "n9"
  - n1: "n9"
    n2: "n8"
    n3: "n10"
  - n1: "n10"
    n2: "n6"
    n3: "n11"
